
all:
	g++ -c classButton.cpp
	g++ -c commonProperty.cpp
	g++ -c buttonProperty.cpp
	g++ -c groupProperty.cpp
	g++ -c fieldProperty.cpp
	g++ -c tableProperty.cpp
	mv *.o ./obj/

clean:
	rm ./obj/*.o
	rm *.o